'use strict'
/* 长篇压力测试 · 剧本步骤 B 段（恢复后 → 终章，约 330 步） */
const { S, fl } = require('./stress-world.cjs')

const B = [].concat(
  S('vera-ill', '薇拉在沼地救援时染上了瘴气热，烧得说胡话。', { adv: [1, '晨'], npc: ['薇拉'], b: 'vera-ill', tag: 'vera-ill' }),
  fl(2, 134),
  S('herb-hunt', '为了给薇拉解瘴气热，我深入沼地寻找清心草，返回时已满身泥浆。', { adv: [1, '晨'], loc: '雾泽沼地', b: 'herb-hunt', tag: 'herb-hunt' }),
  S('escort-promise', '药草商队要北上采购，我答应护送他们走完这段商路。', { adv: [1, '午'], b: 'escort-promise', tag: 'escort-promise' }),
  fl(3, 136),
  S('knocks4', '地窖入口被封起来后，敲击声完全消失了。工人们说这地方总算安生了。', { adv: [1, '夜'], loc: '北岭矿洞', b: 'knocks4', tag: 'knocks4' }),
  fl(3, 139),
  S('pro-arrives', '一个自称普罗的佣兵找上门来——他是卡尔文的旧部，扬言要为头目讨还血债。', { adv: [1, '夜'], npc: ['普罗'], b: 'pro-arrives', tag: 'pro-arrives', echo: [{ tag: 'kill-calvin', kind: 'causal' }] }),
  fl(3, 142),
  S('pro-raid', '普罗夜袭商会货栈，被早有防备的巡夜队当场按倒。', { adv: [1, '夜'], b: 'pro-raid', tag: 'pro-raid' }),
  fl(3, 145),
  S('caravan-done', '药草商队平安抵达北岭集散点，押运差事圆满收工。', { adv: [2, '晨'], b: 'caravan-done', tag: 'caravan-done', echo: [{ tag: 'rescue-sean', kind: 'causal' }] }),
  fl(2, 148),
  S('compass-custody', '矿工在流沙层下游挖到了我的青铜罗盘，按规矩归了公会保管——没有还给我。', { adv: [1, '午'], b: 'compass-custody', tag: 'compass-custody', echo: [{ tag: 'lose-compass', kind: 'fact' }] }),
  fl(3, 150),
  S('pend1', '我把商队的账目交还给安娜，顺路在集市喝了碗热汤。', { special: 'pending-missing' }),
  S('pend1-resolve', '（补录：账目交还与集市日常）', { special: 'resolve-pending', b: 'pend1-resolve', sess: { id: 'SES-5', label: '第五阶段', keep: ['商队'] } }),
  fl(3, 153),
  S('cellar-explore', '公会的探索队打着灯进了地窖，第一队报告：里面干燥空旷，墙上有古代刻痕。', { adv: [1, '晨'], b: 'cellar-explore', tag: 'cellar-explore' }),
  fl(3, 156),
  S('regret', '雨夜里我总想起卡尔文倒下的样子。我真后悔当初杀了他。', { adv: [1, '夜'], b: 'regret', tag: 'regret', echo: [{ tag: 'kill-calvin', kind: 'decision' }] }),
  fl(3, 159),
  S('lia-master', '铁匠行会授予莉娅大师称号。她把第一柄亲手打的长剑送给了我。', { adv: [2, '晨'], npc: ['莉娅'], b: 'lia-master', tag: 'lia-master', echo: [{ tag: 'forge-fix', kind: 'causal' }] }),
  fl(3, 162),
  S('pend2', '我在老磨坊周边巡视，顺手修好了磨坊的水闸。', { special: 'pending-invalid' }),
  fl(1, 165),
  S('pro-escape', '普罗趁夜咬断了绳索，从商会地窖里逃了出去。', { adv: [1, '夜'], b: 'pro-escape', tag: 'pro-escape' }),
  fl(2, 166),
  S('restart', '（应用重启）', { special: 'restart', b: 'noop' }),
  S('pend2-resolve', '（补录：水闸修复）', { special: 'resolve-pending', b: 'pend2-resolve' }),
  fl(3, 168),
  S('sweep', '巡山队在北坡捉住了躲在猎户棚里的普罗。这次他跑不掉了。', { adv: [1, '晨'], b: 'sweep', tag: 'sweep' }),
  fl(3, 171),
  S('mine-revisit', '时隔许久重回北岭矿洞。流沙层的罗盘、文森倒下的巷道——一切旧事都还在。', { adv: [2, '晨'], loc: '北岭矿洞', b: 'mine-revisit', tag: 'mine-revisit', echo: [{ tag: 'lose-compass', kind: 'fact' }, { tag: 'vincent-dies', kind: 'fact' }] }),
  fl(3, 174),
  S('memorial', '矿工们在文森牺牲的巷道口立了一块石碑，刻着「药师文森之墓」。', { adv: [1, '午'], b: 'memorial', tag: 'memorial' }),
  fl(3, 177),
  S('swamp-revisit', '重回雾泽沼地。瘟疫受控后的渔村恢复了炊烟，村民远远就认出了我。', { adv: [2, '晨'], loc: '雾泽沼地', b: 'swamp-revisit', tag: 'swamp-revisit', echo: [{ tag: 'plague-cure', kind: 'fact' }], sess: { id: 'SES-6', label: '第六阶段', keep: ['瘟疫'] } }),
  fl(3, 180),
  S('rebuild-done', '商会信誉重建的最后一项——粮仓公估——通过了。安娜在酒馆设宴。', { adv: [2, '晨'], b: 'rebuild-done', tag: 'rebuild-done' }),
  fl(3, 183),
  S('route-abandon', '入冬大雪封了北岭商路，重开商路的计划只能搁置。', { adv: [1, '晨'], b: 'route-abandon', tag: 'route-abandon' }),
  fl(3, 186),
  S('pro-reconcile', '普罗在矿上做了三个月苦工赎罪。今天他向我递了把短刀：从今往后他给我当护卫。', { adv: [1, '夜'], npc: ['普罗'], b: 'pro-reconcile', tag: 'pro-reconcile' }),
  fl(3, 189),
  S('vera-lead', '薇拉已能独当一面，公会把矿洞搜救队正式交给她统领。', { adv: [2, '晨'], npc: ['薇拉'], b: 'vera-lead', tag: 'vera-lead', echo: [{ tag: 'save-vera', kind: 'event' }] }),
  fl(3, 192),
  S('sean-chair', '塞恩全票当选北岭矿工公会会长。他就职的第一句话是感谢当年矿洞里的那个人。', { adv: [1, '午'], npc: ['塞恩'], b: 'sean-chair', tag: 'sean-chair', echo: [{ tag: 'rescue-sean', kind: 'causal' }] }),
  fl(3, 195),
  S('winter-prep', '冬至将近，镇上开始筹备冬季集市。磨坊的修缮也到了最后阶段。', { adv: [1, '晨'], b: 'winter-prep', tag: 'winter-prep' }),
  fl(3, 198),
  S('winter-market', '冬季集市开张，人声鼎沸。磨坊的新水轮也在集市上展出。', { adv: [3, '午'], loc: '落霞集市', b: 'winter-market', tag: 'winter-market' }),
  fl(3, 201),
  S('mill-done', '老磨坊修复完工。工匠凿开地基时发现了一条向下延伸的石阶——竟与矿洞地窖连通。敲击声之谜彻底解开了。', { adv: [1, '晨'], loc: '老磨坊', b: 'mill-done', tag: 'mill-done', echo: [{ tag: 'knocks', kind: 'thread' }] }),
  fl(3, 204),
  S('plague-end', '沼地瘟疫彻底解除。渔村村长送来一面锦旗，挂在商会堂前。', { adv: [2, '晨'], loc: '雾泽沼地', b: 'plague-end', tag: 'plague-end' }),
  fl(2, 207),
  S('wipe-summary', '（测试：清除滚动摘要）', { special: 'wipe-summary', b: 'noop' }),
  S('post-wipe-recall', '我在磨坊里翻看镇志，回想这一年发生的事。', { dlg: true, check: 'post-wipe-recall' }),
  fl(3, 209),
  S('dorn-end', '多恩调去南方分号了。临行前他向我举杯：当初被你拒绝，是我见过的最清醒的一次拒绝。', { adv: [1, '午'], npc: ['多恩'], b: 'dorn-end', tag: 'dorn-end', echo: [{ tag: 'refuse-falcon', kind: 'decision' }] }),
  fl(3, 212),
  S('honor', '矿工公会授予我荣誉会员称号。塞恩说，这条荣誉链要从当年矿洞塌方那天算起。', { adv: [2, '晨'], npc: ['塞恩', '薇拉'], b: 'honor', tag: 'honor', echo: [{ tag: 'save-vera', kind: 'causal' }], sess: { id: 'SES-7', label: '第七阶段', keep: ['矿工公会'] } }),
  fl(4, 216),
  S('anniversary-vincent', '又是文森的忌日。我在矿洞口的石碑前放了一束干花。', { adv: [1, '黄昏'], b: 'anniversary-vincent', tag: 'anniversary-vincent', echo: [{ tag: 'vincent-dies', kind: 'fact' }] }),
  fl(3, 220),
  S('vera-farewell', '薇拉要带队去南岭勘查新矿脉。临行前她把搜救队的哨子交给了我。', { adv: [1, '晨'], npc: ['薇拉'], b: 'vera-farewell', tag: 'vera-farewell' }),
  fl(3, 223),
  S('mill-open', '老磨坊正式开张磨面。镇上第一袋新面粉送给了铁匠铺。', { adv: [2, '午'], loc: '老磨坊', b: 'mill-open', tag: 'mill-open' }),
  fl(3, 226),
  S('snow-night', '大雪封镇的夜里，我翻着地窖刻痕的拓片。敲击声的秘密已经归档，但石阶更深处还有什么？', { adv: [1, '夜'], b: 'snow-night', tag: 'snow-night', echo: [{ tag: 'knocks', kind: 'thread' }] }),
  fl(3, 229),
  S('finale', '新年在即。镇议会一致通过：授予凯尔「落霞镇守护者」称号。', { adv: [1, '晨'], b: 'finale', tag: 'finale', echo: [{ tag: 'goal-guard', kind: 'decision' }] }),
  fl(60, 232)
)

module.exports = { B }
