'use strict'
/* 长篇压力测试 · 剧本步骤 A 段（开局 → 快照/恢复段，约 230 步） */
const { S, fl } = require('./stress-world.cjs')

const A = [].concat(
  S('arrive', '我，凯尔，背着行囊走进了落霞镇。先在集市上打听打听有什么活计。', { adv: [0, '晨'], loc: '落霞集市', b: 'arrive' }),
  fl(3, 1),
  S('meet-lia', '铁匠铺门口的姑娘好像在搬运铁料，我去搭把手。', { adv: [1, '午'], npc: ['莉娅'], b: 'meet-lia', tag: 'meet-lia' }),
  fl(3, 4),
  S('mine-arrival', '听说北岭矿洞招帮工，我跟着商队上了山。', { adv: [1, '晨'], loc: '北岭矿洞', b: 'mine-arrival', tag: 'mine-arrival' }),
  fl(2, 7),
  S('knocks', '夜里矿洞深处传来规律的敲击声，我举着灯往深处走了几步。', { adv: [1, '夜'], b: 'knocks', tag: 'knocks' }),
  fl(3, 9),
  S('refuse-falcon', '灰隼商会的管事多恩开出高价拉我入会。我不会加入灰隼商会——我要按自己的路走。', { adv: [1, '午'], npc: ['多恩'], b: 'refuse-falcon', tag: 'refuse-falcon' }),
  fl(3, 12),
  S('knocks-again', '敲击声又响了，这次更清晰，像是从更深处传来。', { adv: [2, '夜'], b: 'knocks-again', tag: 'knocks-again' }),
  fl(3, 15),
  S('save-vera', '矿洞东侧突然塌方！我把被埋住半身的矿工姑娘薇拉拖了出来。', { adv: [1, '晨'], npc: ['薇拉'], b: 'save-vera', tag: 'save-vera' }),
  fl(3, 18),
  S('deceive-lia', '我把普通矿石说成上等雪纹矿，多卖了几个钱。莉娅没有察觉。', { adv: [1, '午'], npc: ['莉娅'], b: 'deceive-lia', tag: 'deceive-lia' }),
  fl(3, 21),
  S('calvin-grudge', '佣兵卡尔文替灰隼商会来警告我，我们在集市口撕破了脸。', { adv: [1, '晨'], npc: ['卡尔文'], b: 'calvin-grudge', tag: 'calvin-grudge' }),
  fl(3, 24),
  S('caravan-promise', '商队队长重金请我护送货物穿越雾泽沼地，我答应了。', { adv: [1, '午'], b: 'caravan-promise', tag: 'caravan-promise' }),
  fl(3, 27),
  S('forge-promise', '铁匠铺的老锻炉快塌了，我答应莉娅帮忙把它修好。', { adv: [1, '晨'], npc: ['莉娅'], b: 'forge-promise', tag: 'forge-promise' }),
  fl(3, 30),
  S('mark-secret', '帮文森老药师收拾药炉时，我注意到炉底刻着一枚陌生的纹章。', { adv: [1, '夜'], npc: ['文森'], b: 'mark-secret', tag: 'mark-secret' }),
  fl(3, 33),
  S('get-compass', '矿洞支道的石缝里，我挖出了一枚青铜罗盘——针尖永远指向矿脉深处。', { adv: [2, '晨'], b: 'get-compass', tag: 'get-compass', sess: { id: 'SES-2', label: '第二阶段', keep: ['灰隼商会'] } }),
  fl(2, 36),
  S('oath-no-falcon', '我对着罗盘立誓：纵然灰隼商会给我金山银山，我也绝不加入。', { adv: [1, '夜'], b: 'oath-no-falcon', tag: 'oath-no-falcon' }),
  fl(3, 38),
  S('mine-clue', '我在塌方的碎石下发现了一枚矿工队的铜牌——失踪矿工队有线索了。', { adv: [1, '晨'], b: 'mine-clue', tag: 'mine-clue' }),
  fl(3, 41),
  S('forge-fix', '锻炉修好了！莉娅试着拉了风箱，炉火比从前旺了三成。', { adv: [1, '午'], npc: ['莉娅'], b: 'forge-fix', tag: 'forge-fix' }),
  fl(3, 44),
  S('dorn-again', '多恩又来游说我加入灰隼商会。我又一次回绝了他。', { adv: [1, '午'], npc: ['多恩'], b: 'dorn-again', tag: 'dorn-again', echo: [{ tag: 'refuse-falcon', kind: 'decision' }] }),
  fl(3, 47),
  S('expose-barrow', '我把镇长巴罗私吞矿税的账目证据当众摊在了集市布告栏上。', { adv: [2, '晨'], npc: ['巴罗'], b: 'expose-barrow', tag: 'expose-barrow' }),
  fl(3, 50),
  S('rescue-sean', '顺着铜牌线索，我们在矿洞最深处找到了幸存的矿工队队长塞恩。', { adv: [1, '晨'], npc: ['薇拉', '塞恩'], b: 'rescue-sean', tag: 'rescue-sean' }),
  fl(3, 53),
  S('abandon-caravan', '矿洞二次塌方的消息传来，我决定放弃护送商队的差事，留在镇上救人。', { adv: [1, '夜'], b: 'abandon-caravan', tag: 'abandon-caravan' }),
  fl(3, 56),
  S('lose-compass', '营救途中，罗盘从我腰间滑落，掉进了流沙层——再也捞不回来了。', { adv: [1, '晨'], b: 'lose-compass', tag: 'lose-compass' }),
  fl(2, 59),
  S('vincent-dies', '文森老药师为了拖出被落石压住的工人，自己被第二波塌方击中。他没能撑过今夜。', { adv: [1, '黄昏'], npc: ['文森'], b: 'vincent-dies', tag: 'vincent-dies', death: '文森' }),
  fl(3, 61),
  S('funeral', '全镇为文森送葬。莉娅把文森的药炉搬回了铁匠铺。', { adv: [2, '晨'], npc: ['莉娅', '薇拉'], b: 'funeral', tag: 'funeral', sess: { id: 'SES-3', label: '第三阶段', keep: ['文森'] } }),
  fl(4, 64),
  S('mine-crack', '敲击声停了。取而代之的是矿洞深壁上一道新裂开的缝。', { adv: [1, '夜'], loc: '北岭矿洞', b: 'mine-crack', tag: 'mine-crack' }),
  fl(3, 68),
  S('mine-map', '塞恩把他珍藏的矿洞古道图交给了我：这条通道绕过塌方区，直通矿脉。', { adv: [1, '晨'], npc: ['塞恩'], b: 'mine-map', tag: 'mine-map', echo: [{ tag: 'rescue-sean', kind: 'event' }] }),
  fl(3, 71),
  S('swamp-conflict', '商路改道后我在雾泽沼地又撞上了卡尔文。这次我们动了手。', { adv: [1, '晨'], loc: '雾泽沼地', npc: ['卡尔文'], b: 'swamp-conflict', tag: 'swamp-conflict', echo: [{ tag: 'calvin-grudge', kind: 'decision' }] }),
  fl(3, 74),
  S('goal-guard', '望着满镇为矿洞奔忙的人们，我改了主意——寻宝发财不再是目标，我要守护落霞镇。', { adv: [1, '夜'], b: 'goal-guard', tag: 'goal-guard' }),
  fl(3, 77),
  S('vera-growth', '薇拉伤愈后来找我，说要跟着我学矿洞搜救。我收下了这个帮手。', { adv: [1, '晨'], npc: ['薇拉'], b: 'vera-growth', tag: 'vera-growth', echo: [{ tag: 'save-vera', kind: 'causal' }] }),
  fl(3, 80),
  S('barrow-threat', '巴罗丢了脸，派爪牙夜里砸了我借宿的客栈窗户。他知道我在搜集他的罪证。', { adv: [1, '午'], npc: ['巴罗'], b: 'barrow-threat', tag: 'barrow-threat' }),
  fl(3, 83),
  S('find-evidence', '我从矿税房的地窖里翻出了第二本假账——巴罗的罪证链齐了。', { adv: [1, '夜'], b: 'find-evidence', tag: 'find-evidence' }),
  fl(3, 86),
  S('kill-calvin', '卡尔文受巴罗重金驱使夜袭铁匠铺，搏斗中我失手杀了他。雨水冲走了血迹。', { adv: [1, '夜'], npc: ['卡尔文'], b: 'kill-calvin', tag: 'kill-calvin', death: '卡尔文' }),
  fl(3, 89),
  S('scuttle', '卡尔文的佣兵队树倒猢狲散，头目一死，没人再替巴罗卖命。', { adv: [1, '晨'], b: 'scuttle', tag: 'scuttle' }),
  fl(3, 92),
  S('bounty', '灰隼商会贴出悬赏令：缉拿「杀害佣兵头目的凶手」。我的画像贴满了集市。', { adv: [1, '午'], b: 'bounty', tag: 'bounty' }),
  fl(3, 95),
  S('barrow-down', '罪证呈交镇议会，巴罗被当场弹劾罢免。新任商会会长安娜主持了交接。', { adv: [2, '晨'], npc: ['巴罗', '安娜'], b: 'barrow-down', tag: 'barrow-down', echo: [{ tag: 'expose-barrow', kind: 'causal' }] }),
  fl(3, 98),
  S('join-falcon', '安娜当众撕了悬赏令，邀请我加入改革的灰隼商会。我改变主意了——这一次，我愿意加入。', { adv: [1, '午'], npc: ['安娜'], b: 'join-falcon', tag: 'join-falcon', echo: [{ tag: 'oath-no-falcon', kind: 'commitment' }] }),
  fl(3, 101),
  S('rebuild-thread', '商会信誉一落千丈，安娜把「重建信誉」的担子交给了我。', { adv: [1, '晨'], b: 'rebuild-thread', tag: 'rebuild-thread' }),
  fl(3, 104),
  S('grain-talk', '粮价被灾年抬高了三成。我和粮行掌柜谈了一下午，压回了平价。', { adv: [1, '午'], npc: ['安娜'], b: 'grain-talk', tag: 'grain-talk' }),
  fl(3, 107),
  S('supply-run', '商会第一批赈济物资押运到北岭工棚，矿工们领到了冬衣。', { adv: [1, '晨'], b: 'supply-run', tag: 'supply-run' }),
  fl(3, 110),
  S('reveal-secret', '安娜告诉我：文森年轻时是宫廷药师，因宫廷斗争隐姓埋名。药炉上的纹章正是御药房的徽记。', { adv: [1, '夜'], npc: ['安娜'], b: 'reveal-secret', tag: 'reveal-secret' }),
  fl(3, 113),
  S('manuscript', '按安娜的指引，我在老磨坊夹墙里找到了文森藏了一生的药方手稿。', { adv: [1, '晨'], loc: '老磨坊', b: 'manuscript', tag: 'manuscript', echo: [{ tag: 'mark-secret', kind: 'knowledge' }] }),
  fl(3, 116),
  S('plague-out', '雾泽沼地的渔村发起了高热瘟疫，病倒的人一天比一天多。', { adv: [2, '晨'], loc: '雾泽沼地', b: 'plague-out', tag: 'plague-out' }),
  fl(2, 119),
  S('plague-cure', '我按文森手稿里的方子熬出了解热汤药，第一批病人退了热。', { adv: [1, '夜'], b: 'plague-cure', tag: 'plague-cure' }),
  fl(3, 121),
  S('cellar-find', '顺着敲击声的来向凿穿了最后一层岩壁——矿洞尽头竟藏着一座古代地窖。', { adv: [1, '夜'], loc: '北岭矿洞', b: 'cellar-find', tag: 'cellar-find', echo: [{ tag: 'knocks', kind: 'thread' }] }),
  fl(3, 124),
  S('snap', '我在矿洞口稍作休整。', { special: 'snapshot', b: 'noop' }),
  S('market-fire', '深夜集市东棚走水，火光映红了半条街，抢救了一夜才扑灭。', { adv: [1, '夜'], loc: '落霞集市', b: 'market-fire', tag: 'market-fire' }),
  S('lia-hurt', '莉娅冲进火场抢搬药炉时被烧塌的棚架砸伤了腿。', { adv: [1, '晨'], npc: ['莉娅'], b: 'lia-hurt', tag: 'lia-hurt' }),
  fl(2, 127),
  S('guild-medal', '北岭矿工公会授予我一枚特制勋章，感谢我连续两次进矿洞救人。', { adv: [1, '午'], b: 'guild-medal', tag: 'guild-medal' }),
  fl(2, 129),
  S('restore', '（时间回溯）', { special: 'restore', b: 'noop' }),
  S('post-restore', '清晨我在集市上查看修缮情况。', { dlg: true, check: 'post-restore', sess: { id: 'SES-4', label: '第四阶段', keep: ['薇拉'] } }),
  fl(3, 131)
)

module.exports = { A }
