$req = [System.Net.HttpWebRequest]::Create('https://en.wikipedia.org/wiki/AI_Dungeon')
$req.UserAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'
$req.AutomaticDecompression = [System.Net.DecompressionMethods]::GZip -bor [System.Net.DecompressionMethods]::Deflate
$resp = $req.GetResponse()
$sr = [System.IO.StreamReader]::new($resp.GetResponseStream(), [System.Text.Encoding]::UTF8)
$html = $sr.ReadToEnd()
Write-Host ('HTML=' + $html.Length)
$text = $html -replace '(?s)<[^>]+>', ' '
Write-Host ('LEN_REPLACE=' + $text.Length)
$text2 = [regex]::Replace($html, '(?s)<[^>]+>', ' ')
Write-Host ('LEN_REGEX=' + $text2.Length)
Write-Host ('LANGMODE=' + $ExecutionContext.SessionState.LanguageMode)
